CREATE TABLE CAC (
CAC_NO NUMBER(10) PRIMARY KEY,
CAC_HAV NUMBER(10),
CAC_HDAY DATE,
CAC_PRE NUMBER(10),
CAC_PDAY DATE
);

ALTER TABLE CAC ADD CONSTRAINT CAC_01 FOREIGN KEY (CAC_HAV) REFERENCES CE(CE_NO);
ALTER TABLE CAC ADD CONSTRAINT CAC_02 FOREIGN KEY (CAC_PRE) REFERENCES CE(CE_NO);

SELECT * FROM CAC WHERE CAC_NO = ?;

INSERT INTO CAC VALUES (?,?,?,?,?,?);

DELETE CAC WHERE CAC_NO = ?;

UPDATE CAC SET CAC_NO = ? WHERE CAC_NO = ?;
UPDATE CAC SET CAC_HAV = ? WHERE CAC_NO = ?;
UPDATE CAC SET CAC_PRE = ? WHERE CAC_NO = ?;
UPDATE CAC SET CAC_DAY = ? WHERE CAC_NO = ?;
UPDATE CAC SET CAC_COM = ? WHERE CAC_NO = ?;
