CREATE TABLE CACT (
CACT_NO NUMBER(10) PRIMARY KEY, 
CACT_CNO NUMBER(10),
CACT_LCOD VARCHAR2(100),
CACT_MCOD VARCHAR2(100),
CACT_TOT NUMBER(10)
);

ALTER TABLE CACT ADD CONSTRAINT CACT_01 FOREIGN KEY (CACT_CNO) REFERENCES CE(CE_NO);
ALTER TABLE CACT ADD CONSTRAINT CACT_02 FOREIGN KEY (CACT_LCOD) REFERENCES JCL(JCL_COD);
ALTER TABLE CACT ADD CONSTRAINT CACT_03 FOREIGN KEY (CACT_MCOD) REFERENCES JCM(JCM_COD);

SELECT * FROM CACT WHERE CACT_NO = ?;
SELECT * FROM CACT WHERE CACT_CNO = ?;
SELECT * FROM CACT WHERE CACT_LCOD LIKE '%?%';
SELECT * FROM CACT WHERE CACT_MCOD LIKE '%?%';

INSERT INTO CACT VALUES (?,?,?,?);

DELETE CACT WHERE CACT_NO = ?;
DELETE CACT WHERE CACT_CNO = ?;
DELETE CACT WHERE CACT_LCOD = ?;
DELETE CACT WHERE CACT_MCOD = ?;

UPDATE CACT SET CACT_CNO = ? WHERE CACT_NO = ?;
UPDATE CACT SET CACT_LCOD = ? WHERE CACT_NO = ?;
UPDATE CACT SET CACT_MCOD = ? WHERE CACT_NO = ?;
