
CREATE TABLE CE (
CE_NO NUMBER(10) PRIMARY KEY, 
CE_NAME VARCHAR2(100), 
CE_EXP VARCHAR2(4000) NOT NULL, 
CE_SUB VARCHAR2(100), 
CE_LINK VARCHAR2(100)
);

SELECT * FROM CE WHERE CE_NO = ?;
SELECT * FROM CE WHERE CE_NAME LIKE = '%?%';
SELECT * FROM CE WHERE CE_EXP LIKE = '%?%';
SELECT * FROM CE WHERE CE_SUB LIKE = '%?%';

SELECT DISTINCT * FROM CE A LEFT OUTER JOIN CACT B ON A.CE_NO = B.CACT_CNO;

INSERT INTO CE values (?,?,?,?);

DELETE CE WHERE CE_NO=?;
DELETE CE WHERE CE_NAME=?;

UPDATE CE SET CE_NAME=? WHERE CE_NO=?;
UPDATE CE SET CE_EXP=? WHERE CE_NO=?;
UPDATE CE SET CE_LINK=? WHERE CE_NO=?;