
CREATE TABLE CP (
CP_ID VARCHAR2(30),
CP_NO NUMBER(10),
CP_CACNO NUMBER(10),
CP_COMNO NUMBER(10),
CP_PMNO NUMBER(10),
CP_CPPNO NUMBER(10),
CP_JCLCOD VARCHAR2(30)
);

ALTER TABLE CP ADD CONSTRAINT CP_01 FOREIGN KEY (CP_ID) REFERENCES CUSTOMER(C_ID);
ALTER TABLE CP ADD CONSTRAINT CP_02 FOREIGN KEY (CP_CACNO) REFERENCES CAC(CAC_NO);
ALTER TABLE CP ADD CONSTRAINT CP_03 FOREIGN KEY (CP_COMNO) REFERENCES COM(COM_NO);
ALTER TABLE CP ADD CONSTRAINT CP_04 FOREIGN KEY (CP_PMNO) REFERENCES PM(PM_NO);
ALTER TABLE CP ADD CONSTRAINT CP_05 FOREIGN KEY (CP_CPPNO) REFERENCES CPP(CPP_NO);
ALTER TABLE CP ADD CONSTRAINT CP_06 FOREIGN KEY (CP_JCLCOD) REFERENCES JCL(JCL_COD);
ALTER TABLE CP ADD CONSTRAINT CP_07 UNIQUE (CP_ID, CP_NO);

SELECT * FROM CP WHERE CP_ID = ?;
SELECT * FROM CP WHERE CP_ID = ?, CP_NO = ?;

SELECT * FROM CP A LEFT OUTER JOIN CAC B ON A.CP_CACNO = B.CAC_NO;
SELECT * FROM CP A LEFT OUTER JOIN COM B ON A.CP_COMNO = B.COM_NO;
SELECT * FROM CP A LEFT OUTER JOIN PM B ON A.CP_PMNO = B.PM_NO;
SELECT * FROM CP A LEFT OUTER JOIN CPP B ON A.CP_CPPNO = B.CPP_NO;
SELECT * FROM CP A LEFT OUTER JOIN JCL B ON A.CP_JCLCOD = B.JCL_COD;

DELETE CP WHERE CP_ID = ?, CP_NO = ?;

UPDATE CP SET CP_CACNO = ? WHERE CP_ID = ?, CP_NO = ?;
UPDATE CP SET CP_COMNO = ? WHERE CP_ID = ?, CP_NO = ?;
UPDATE CP SET CP_PMNO = ? WHERE CP_ID = ?, CP_NO = ?;
UPDATE CP SET CP_CPPNO = ? WHERE CP_ID = ?, CP_NO = ?;
UPDATE CP SET CP_JCLCOD = ? WHERE CP_ID = ?, CP_NO = ?;



