
CREATE TABLE CPP (
CPP_NO NUMBER(10) PRIMARY KEY, 
CPP_NAME VARCHAR2(100) NOT NULL, 
CPP_EXP VARCHAR2(4000),
CPP_ST DATE, 
CPP_END DATE
);

SELECT * FROM CPP WHERE CPP_NO = ?;

SELECT * FROM CPP A RIGHT OUTER JOIN CP B WHERE A.CPP_NO = B.CP_CPPNO;

INSERT INTO CPP VALUES (?,?,?,?,?)

DELETE CPP WHERE CPP_NO = ?;

UPDATE CPP SET CPP_NAME = ? WHERE CPP_NO = ?;
UPDATE CPP SET CPP_ST = ? WHERE CPP_NO = ?;
UPDATE CPP SET CPP_END = ? WHERE CPP_NO = ?;
UPDATE CPP SET CPP_FILE = ? WHERE CPP_NO = ?;
UPDATE CPP SET CPP_LINK = ? WHERE CPP_NO = ?;
