CREATE TABLE CST (
CST_NO NUMBER(10) PRIMARY KEY,
CST_MCOD VARCHAR2(30),
CST_DLA NUMBER(10),
CST_DTOT NUMBER(10),
CST_SLA NUMBER(10),
CST_STOT NUMBER(10)
)


SELECT * FROM CST WHERE CPL_NO = ?;

INSERT INTO CST VALUES (?,?,?,?,?);

DELETE CST WHERE CST_NO = ?;
DELETE CST WHERE CST_MCOD LIKE '%?%';
DELETE CST WHERE CST_DLA = ?;
DELETE CST WHERE CST_SLA = ?;

UPDATE CST SET CST_MCOD = ? WHERE CST_NO = ?;
UPDATE CST SET CST_DLA = ? WHERE CST_NO = ?;
UPDATE CST SET CST_SLA = ? WHERE CST_NO = ?;
