
CREATE TABLE JCL (
JCL_NO NUMBER(10) NOT NULL, 
JCL_COD VARCHAR2(30) PRIMARY KEY, 
JCL_NAME VARCHAR2(30) NOT NULL,
JCL_EXP VARCHAR2(4000) NOT NULL
);

SELECT * FROM JCL WHERE JCL_NO = ?;
SELECT * FROM JCL WHERE JCL_COD LIKE '%?%';
SELECT * FROM JCL WHERE JCL_NAME LIKE '%?%';
SELECT * FROM JCL WHERE JCL_EXP LIKE '%?%';

SELECT DISTINCT * FROM JCL A RIGHT OUTER JOIN JCM B ON A.JCL_COD = B.JCM_LCOD;

INSERT INTO JCL VALUES (?,?,?,?);

DELETE JCL WHERE JCL_NO = ?;

UPDATE JCL SET JCL_COD = ? WHERE JCL_COD = ?;
UPDATE JCL SET JCL_NAME = ? WHERE JCL_COD = ?;
UPDATE JCL SET JCL_EXP = ? WHERE JCL_EXP = ?;
