
CREATE TABLE JCM (
JCM_NO NUMBER(10) NOT NULL,
JCM_LCOD VARCHAR2(30), 
JCM_COD VARCHAR2(30) PRIMARY KEY, 
JCM_EXP VARCHAR2(4000) NOT NULL, 
JCM_LANG01 NUMBER(10),
JCM_LANG02 NUMBER(10),
JCM_LANG03 NUMBER(10)
);

ALTER TABLE JCM ADD CONSTRAINT JCM_01 FOREIGN KEY (JCM_LCOD) REFERENCES JCL(JCL_COD);
ALTER TABLE JCM ADD CONSTRAINT JCM_02 FOREIGN KEY (JCM_LANG01) REFERENCES LANG(LANG_NO);
ALTER TABLE JCM ADD CONSTRAINT JCM_03 FOREIGN KEY (JCM_LANG02) REFERENCES LANG(LANG_NO);
ALTER TABLE JCM ADD CONSTRAINT JCM_04 FOREIGN KEY (JCM_LANG03) REFERENCES LANG(LANG_NO);

SELECT * FROM JCM WHERE JCM_NO = ?;
SELECT * FROM JCM WHERE JCM_COD LIKE '%?%';
SELECT * FROM JCM WHERE JCM_EXP LIKE '%?%';
SELECT * FROM JCM WHERE JCM_LCOD LIKE '%?%';

SELECT * FROM JCM A RIGHT OUTER JOIN JCL B ON A.JCM_LCOD = B.JCL_COD;
SELECT * FROM JCM A RIGHT OUTER JOIN LANG B ON A.JCM_LANG01 = B.LANG_NO;
SELECT * FROM JCM A RIGHT OUTER JOIN LANG B ON A.JCM_LANG02 = B.LANG_NO;
SELECT * FROM JCM A RIGHT OUTER JOIN LANG B ON A.JCM_LANG03 = B.LANG_NO;

INSERT INTO JCM VALUES (?,?,?,?,?,?);

DELETE JCM WHERE JCM_NO = ?;

UPDATE JCM SET JCM_LCOD = ? WHERE JCM_COD = ?;
UPDATE JCM SET JCM_COD = ? WHERE JCM_COD = ?;
UPDATE JCM SET JCM_EXP = ? WHERE JCM_COD = ?;
UPDATE JCM SET JCM_LANG01 = ? WHERE JCM_COD = ?;
UPDATE JCM SET JCM_LANG02 = ? WHERE JCM_COD = ?;
UPDATE JCM SET JCM_LANG03 = ? WHERE JCM_COD = ?;