
CREATE TABLE LANG (
LANG_NO NUMBER(10) PRIMARY KEY, 
LANG_CO VARCHAR2(30), 
LANG_NAME VARCHAR2(30),
LANG_EXP VARCHAR2(4000)
);

SELECT DISTINCT * FROM LANG A RIGHT OUTER JOIN JCM B ON A.LANG_NO = B.JCM_LANG01;
SELECT DISTINCT * FROM LANG A RIGHT OUTER JOIN JCM B ON A.LANG_NO = B.JCM_LANG02;
SELECT DISTINCT * FROM LANG A RIGHT OUTER JOIN JCM B ON A.LANG_NO = B.JCM_LANG03;


INSERT INTO LANG VALUES (?,?,?);

DELETE LANG WHERE LANG_NO = ?;

UPDATE LANG SET LANG_CO = ? WHERE LANG_NO = ?;
UPDATE LANG SET LANG_NAME = ? WHERE LANG_NO = ?;
UPDATE LANG SET LANG_EXP = ? WHERE LANG_NO = ?;
