CREATE TABLE RE (
RE_NO NUMBER(10) PRIMARY KEY,
RE_BNO NUMBER(10), 
RE_EXP VARCHAR2(4000), 
RE_ID VARCHAR2(30), 
RE_DAY DATE
);

ALTER TABLE RE ADD CONSTRAINT RE_01 FOREIGN KEY (RE_BNO) REFERENCES BBS(BBS_NO);
ALTER TABLE RE ADD CONSTRAINT RE_02 FOREIGN KEY (RE_ID) REFERENCES CUSTOMER(C_ID);

select * from re;
SELECT * FROM RE WHERE RE_ID = ?;
SELECT * FROM RE WHERE RE_EXP = ?;
SELECT * FROM RE WHERE RE_ID = ?, RE_DAY = ?;

INSERT INTO RE VALUES (?,?,?,?);

DELETE RE WHERE RE_NO = ?;

select * from bbs;
select * from re;

insert into re values (reno.nextval,24,'123','123',sysdate);

UPDATE RE SET RE_EXP = ? WHERE RE_NO = ?;

CREATE SEQUENCE RE_SEQ
START WITH 1
INCREMENT BY 1;

